### ISSUE TITLE
sku 动态生成的table中有默认选项input框的话，有好的data结构推荐吗？

### ISSUE THREAD

**Issue by yangyiru** [rossroma/vue-sku#1]
![image](https://user-images.githubusercontent.com/16080274/46139377-f792de00-c280-11e8-9547-6d733bfa1245.png)
类似红圈部分是固定，里面的input数据应该怎么放？

**Comment by rossroma** [comment]
> ![image](https://user-images.githubusercontent.com/16080274/46139377-f792de00-c280-11e8-9547-6d733bfa1245.png)
> 类似红圈部分是固定，里面的input数据应该怎么放？

我完善了一下代码，加入了规格、价格、库存等信息，希望能对你有所帮助

**Comment by okchenyi** [comment]
> > ![image](https://user-images.githubusercontent.com/16080274/46139377-f792de00-c280-11e8-9547-6d733bfa1245.png)
> > 类似红圈部分是固定，里面的input数据应该怎么放？
> 
> 我完善了一下代码，加入了规格、价格、库存等信息，希望能对你有所帮助

有些时候添加产品规格时 会报错  Cannot read property 'price' of undefined

**Comment by okchenyi** [comment]
> > ![image](https://user-images.githubusercontent.com/16080274/46139377-f792de00-c280-11e8-9547-6d733bfa1245.png)
> > 类似红圈部分是固定，里面的input数据应该怎么放？
> 
> 我完善了一下代码，加入了规格、价格、库存等信息，希望能对你有所帮助

几率性添加产品规格时会报 Cannot read property 'isUse' of undefined

**Comment by blackcai** [comment]
已复现该报错会出现的情况：
1. 当产品规格重复时，会出现该bug。
2. 当产品规格名称为空时会出现，且有多个空规格名称的时候会出现。
---
后续加入手动触发改变规格且不能为空，校验是否重复等。
